name: project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies: 
  get_cli: ^1.8.4
  flutter_lints: ^2.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.9
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.8.0

flutter: 
  uses-material-design: true

